import type { IMerchSchema } from "@app/store";
import mongoose from "mongoose";
import { v4 } from "uuid";
const Schema = mongoose.Schema;

const merchSchema = new Schema<IMerchSchema>(
  {
    storeId: { type: Schema.Types.ObjectId, ref: "Store", require: true },
    // universal id
    uid: { type: String, default: v4 },
    // unique item id
    merchId: { type: String, default: v4 },
    // productId: generated by stripe
    productId: { type: String },
    // priceId: generated by stripe
    priceId: { type: String },
    // currency: { type: String, default: "usd" },
    thumbnail: { type: String, default: "" },
    catalog: [{ type: String, default: "" }],
    hero: { type: String, default: "" },
    name: { type: String, default: "" },
    description: { type: String, default: "" },
    inStock: { type: Number, default: 1 },
    onHold: { type: Number, default: 0 },
    cost: { type: Number, default: 0 },
  },
  { timestamps: true }
);
const Merch = mongoose.model("Merch", merchSchema);
export default Merch;
