import mongoose from "mongoose";
import { v4 } from "uuid";
const Schema = mongoose.Schema;

const storeSchema = new Schema(
  {
    ownerId: { type: String, require: true },
    appId: { type: String, require: true },
    storeId: { type: String, default: v4, require: true, unique: true },
    // account id generated by stripe
    accountId: { type: String },
    currency: { type: String, default: "usd" },
    name: { type: String, default: "" },
    pageName: { type: String, default: "" },
    title: { type: String, default: "" },
    body: { type: String, default: "" },
    email: { type: String, default: "" },
    hero: { type: String, default: "" },
    isRegistered: { type: String, default: false },
    termsOfService: { type: String, default: false },
    inventory: [{ type: Schema.Types.ObjectId, ref: "Merch" }],
  },
  { timestamps: true }
);
const Store = mongoose.model("Store", storeSchema);
export default Store;
