import type { ISubscriptionSchema } from "@app/app";
import mongoose from "mongoose";
import { v4 } from "uuid";
const Schema = mongoose.Schema;

const subcriptionSchema = new Schema<ISubscriptionSchema>(
  {
    // universal id
    subscriptionId: { type: String, default: v4 },
    // productId: generated by stripe
    productId: { type: String },
    // priceId: generated by stripe
    priceId: { type: String },
    // currency: { type: String, default: "usd" },
    thumbnail: { type: String, default: "" },
    subscriptionLink: { type: String, default: "" },
    name: { type: String, default: "" },
    description: { type: String, default: "" },
    cost: { type: Number, default: 0 },
  },
  { timestamps: true }
);
const Subscription = mongoose.model("Subscription", subcriptionSchema);
export default Subscription;
