module.exports = {
  port: process.env.PORT,
  uri: process.env.MONGOOSE_URI,
  clientUrl: process.env.CLIENT_URL,
  clientUrlAlt: process.env.CLIENT_URL_ALT,
  isDev: process.env.NODE_ENV === "development" || process.env.NODE_ENV === "dev",
  isProduction: process.env.NODE_ENV === "production",
  accessTokenSecret: process.env.ACCESS_TOKEN_SECRET,
  refreshTokenSecret: process.env.REFRESH_TOKEN_SECRET,
  appSecret: process.env.APP_SECRET,
  accessTokenName: process.env.COOKIE_NAME,
  refreshTokenName: process.env.COOKIE_NAME_2,
  mongooseUser: process.env.MONGOOSE_USERNAME,
  mongoosePassword: process.env.MONGOOSE_PASSWORD,
  jwtPrivateKey: process.env.JWT_PRIVATE_KEY,
  jwtPublicKey: process.env.JWT_PUBLIC_KEY,
  appId: process.env.APP_ID,
  baseUrl: process.env.BASE_URL,
  translatorKey: process.env.TRANSLATOR_AKI_KEY,
  cookieDomain: process.env.COOKIE_DOMAIN,
  awsBucketName: process.env.AWS_BUCKET_NAME,
  awsImageUrl: process.env.AWS_IMAGE_URL,
  awsRegion: process.env.AWS_REGION,
  awsConsoleLogin: process.env.AWS_CONSOLE_LOGIN,
  awsUsername: process.env.AWS_USERNAME,
  awsPassword: process.env.AWS_PASSWORD,
  awsSecretKey: process.env.AWS_SECRET_KEY,
  awsAccessKey: process.env.AWS_ACCESS_KEY,
  awsApiVersion: process.env.AWS_ACCESS_KEY,
};
